<?php

declare(strict_types=1);

namespace MetabytesSRO\EPost\Api;

use GuzzleHttp\Client as HttpClient;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ClientException;
use InvalidArgumentException;
use MetabytesSRO\EPost\Api\Exception\ErrorException;
use MetabytesSRO\EPost\Api\Exception\InvalidFileFormatException;
use MetabytesSRO\EPost\Api\Exception\MissingAttachmentException;
use MetabytesSRO\EPost\Api\Exception\MissingAuthorizationTokenException;
use MetabytesSRO\EPost\Api\Exception\MissingEnvelopeException;
use MetabytesSRO\EPost\Api\Exception\MissingPreconditionException;
use MetabytesSRO\EPost\Api\Exception\MissingRecipientException;
use MetabytesSRO\EPost\Api\Metadata\DeliveryOptions;
use MetabytesSRO\EPost\Api\Metadata\Envelope;

/**
 * A letter to send through the E-POSTBUSINESS API, and the client for the
 * /api/Letter endpoints (sending, status queries, queue management).
 *
 * API errors (HTTP 4xx) are converted to ErrorException. Timeouts and connection
 * failures (GuzzleHttp\Exception\ConnectException) are not caught; callers should
 * handle these themselves.
 *
 * Status queries are rate limited by the API: calls must be at least 5 seconds
 * apart, otherwise the API answers with HTTP 429 (ErrorException::isRateLimited()).
 */
class Letter
{
    public const API_ENDPOINT = 'https://api.epost.docuguide.com';

    private bool $testEnvironment = false;
    private ?string $testEmail = null;
    private ?AccessToken $accessToken = null;
    private ?Envelope $envelope = null;
    private ?string $coverLetterPath = null;
    private ?string $attachmentPath = null;
    private ?DeliveryOptions $deliveryOptions = null;
    private ?string $letterId = null;

    /**
     * @param ClientInterface|null $httpClient Pre-configured Guzzle client. When given, it is used as is:
     *                                         it must carry the base URI and the Authorization header.
     */
    public function __construct(
        private readonly ?ClientInterface $httpClient = null,
    ) {}

    public function setAccessToken(AccessToken $accessToken): self
    {
        $this->accessToken = $accessToken;

        return $this;
    }

    /**
     * @throws MissingAuthorizationTokenException
     */
    public function getAccessToken(): AccessToken
    {
        if ($this->accessToken === null) {
            throw new MissingAuthorizationTokenException('An AccessToken instance must be passed');
        }

        return $this->accessToken;
    }

    public function setEnvelope(Envelope $envelope): self
    {
        $this->envelope = $envelope;

        return $this;
    }

    /**
     * @throws MissingEnvelopeException
     * @throws MissingRecipientException
     */
    public function getEnvelope(): Envelope
    {
        if ($this->envelope === null) {
            throw new MissingEnvelopeException('No Envelope provided! Provide one beforehand');
        }
        if ($this->envelope->getData() === null) {
            throw new MissingRecipientException('No recipient provided! Add them beforehand');
        }

        return $this->envelope;
    }

    /**
     * Path to a PDF used as cover letter instead of the standard cover sheet generated by the API.
     *
     * @throws InvalidFileFormatException when the file does not exist or is not a PDF
     */
    public function setCoverLetter(?string $coverLetterPath): self
    {
        if ($coverLetterPath !== null && $coverLetterPath !== '') {
            $this->assertPdf($coverLetterPath, 'cover letter');
        }
        $this->coverLetterPath = $coverLetterPath;

        return $this;
    }

    public function getCoverLetter(): ?string
    {
        return $this->coverLetterPath;
    }

    /**
     * Path to the PDF/A document to send.
     *
     * @throws InvalidFileFormatException when the file does not exist or is not a PDF
     */
    public function setAttachment(string $attachmentPath): self
    {
        $this->assertPdf($attachmentPath, 'attachment');
        $this->attachmentPath = $attachmentPath;

        return $this;
    }

    /**
     * @throws MissingAttachmentException
     */
    public function getAttachment(): string
    {
        if ($this->attachmentPath === null || $this->attachmentPath === '') {
            throw new MissingAttachmentException('No attachment provided! Please add an attachment.');
        }

        return $this->attachmentPath;
    }

    public function setDeliveryOptions(?DeliveryOptions $deliveryOptions): self
    {
        $this->deliveryOptions = $deliveryOptions;

        return $this;
    }

    public function getDeliveryOptions(): ?DeliveryOptions
    {
        return $this->deliveryOptions;
    }

    public function setLetterId(?string $letterId): self
    {
        $this->letterId = $letterId;

        return $this;
    }

    /**
     * @throws MissingPreconditionException when no letter ID was set or received from send()
     */
    public function getLetterId(): string
    {
        if ($this->letterId === null || $this->letterId === '') {
            throw new MissingPreconditionException('No letter id provided! Set letter id beforehand');
        }

        return $this->letterId;
    }

    public function setTestEnvironment(bool $testEnvironment): self
    {
        $this->testEnvironment = $testEnvironment;

        return $this;
    }

    /**
     * Send the letter in test mode: the API processes it, emails the result as PDF to
     * this address and does not print or post anything.
     */
    public function setTestEmail(?string $testEmail): self
    {
        $this->testEmail = $testEmail;

        return $this;
    }

    public function getTestEmail(): ?string
    {
        return $this->testEmail;
    }

    public function isTestEnvironment(): bool
    {
        return $this->testEnvironment;
    }

    /**
     * The JSON payload for this letter as expected by POST /api/Letter.
     *
     *
     * @throws MissingEnvelopeException
     * @throws MissingRecipientException
     * @throws MissingAttachmentException
     * @return array<string, mixed>
     */
    public function buildLetterPayload(): array
    {
        $payload = $this->getEnvelope()->getData() ?? [];

        if ($this->coverLetterPath !== null && $this->coverLetterPath !== '') {
            $payload['coverLetter'] = true;
            $payload['coverData'] = $this->encodeFile($this->coverLetterPath);
        } else {
            $payload['coverLetter'] = false;
        }

        $attachmentPath = $this->getAttachment();
        $payload['fileName'] = basename($attachmentPath);
        $payload['data'] = $this->encodeFile($attachmentPath);

        if ($this->deliveryOptions !== null) {
            $payload = array_merge($payload, $this->deliveryOptions->getData());
        }

        if ($this->testEmail !== null && $this->testEmail !== '') {
            $payload['testFlag'] = true;
            $payload['testEMail'] = $this->testEmail;
        }

        return $payload;
    }

    /**
     * Submit this letter. The letter ID assigned by the API is available through getLetterId() afterwards.
     *
     * @throws ErrorException
     */
    public function send(): self
    {
        $results = $this->postLetters([$this->buildLetterPayload()]);
        if (!isset($results[0])) {
            throw new ErrorException(new Error(
                Error::LEVEL_ERROR,
                'E900',
                'The API did not return a letter ID for the submitted letter',
            ));
        }
        $this->letterId = (string) $results[0]->getLetterId();

        return $this;
    }

    /**
     * Submit several letters in one request. The letters are sent with the access
     * token and HTTP client of this instance; the PDFs may total 300 MB per request.
     *
     * @param Letter[] $letters
     *
     *
     * @throws ErrorException
     * @return LetterSendResult[] One result per letter, in the same order
     */
    public function sendBatch(array $letters): array
    {
        if ($letters === []) {
            return [];
        }
        $payloads = [];
        foreach ($letters as $letter) {
            if (!$letter instanceof Letter) {
                throw new InvalidArgumentException('All items must be Letter instances');
            }
            $payloads[] = $letter->buildLetterPayload();
        }

        return $this->postLetters($payloads);
    }

    /**
     * @param list<array<string, mixed>> $payloads
     *
     * @return LetterSendResult[]
     */
    private function postLetters(array $payloads): array
    {
        $body = $this->request('POST', '/api/Letter', ['json' => $payloads]);

        return array_map(static fn(array $item) => LetterSendResult::fromArray($item), Json::decodeList($body));
    }

    /**
     * Status of one letter. Uses the letter ID of this instance when none is given.
     *
     * @throws ErrorException with isNotFound() when the ID is unknown, isRateLimited() when polled too often
     */
    public function getLetterStatus(?string $letterId = null): LetterStatus
    {
        $id = $letterId ?? $this->getLetterId();
        $body = $this->request('GET', '/api/Letter/' . rawurlencode($id));

        return new LetterStatus(Json::decodeObject($body));
    }

    /**
     * Status of several letters by ID.
     *
     * @param int[] $letterIds
     * @param bool $onlyIssues Return only letters with errors or warnings
     *
     * @return LetterStatus[]
     */
    public function getMultipleLetterStatuses(array $letterIds = [], bool $onlyIssues = false): array
    {
        $body = $this->request('POST', '/api/Letter/StatusQuery', [
            'query' => ['onlyIssues' => self::bool($onlyIssues)],
            'json' => array_values($letterIds),
        ]);

        return $this->statusList($body);
    }

    /**
     * Status of all letters created in a date range.
     *
     * @param string $fromDate Start date, e.g. "2024-01-01"
     * @param string $tillDate End date, e.g. "2024-01-31"
     *
     * @return LetterStatus[]
     */
    public function getLetterStatusByDateRange(string $fromDate, string $tillDate, bool $onlyIssues = false): array
    {
        $body = $this->request('GET', '/api/Letter/Date', [
            'query' => [
                'fromDate' => $fromDate,
                'tillDate' => $tillDate,
                'onlyIssues' => self::bool($onlyIssues),
            ],
        ]);

        return $this->statusList($body);
    }

    /**
     * Status of all live letters that have not reached the print centre yet (status 1 to 3).
     *
     * @return LetterStatus[]
     */
    public function getOpenLetters(): array
    {
        return $this->statusList($this->request('GET', '/api/Letter/Open'));
    }

    /**
     * Status of registered letters (Einschreiben) created in a date range.
     *
     * @param bool $onlyOpen Return only letters whose tracking status is not final
     *
     * @return LetterStatus[]
     */
    public function getRegisteredLetterStatus(string $fromDate, string $tillDate, bool $onlyOpen = false): array
    {
        $body = $this->request('GET', '/api/Letter/Registered', [
            'query' => [
                'fromDate' => $fromDate,
                'tillDate' => $tillDate,
                'onlyOpen' => self::bool($onlyOpen),
            ],
        ]);

        return $this->statusList($body);
    }

    /**
     * Status of all letters submitted with the given custom1 value.
     *
     * @return LetterStatus[]
     */
    public function getLetterStatusByCustom1(string $custom1, bool $onlyIssues = false): array
    {
        $body = $this->request('GET', '/api/Letter/Custom1', [
            'query' => ['custom1' => $custom1, 'onlyIssues' => self::bool($onlyIssues)],
        ]);

        return $this->statusList($body);
    }

    /**
     * Status of all letters submitted with the given batch ID.
     *
     * @return LetterStatus[]
     */
    public function getLetterStatusByBatch(int $batchId, bool $onlyIssues = false): array
    {
        $body = $this->request('GET', '/api/Letter/Batch', [
            'query' => ['batchId' => $batchId, 'onlyIssues' => self::bool($onlyIssues)],
        ]);

        return $this->statusList($body);
    }

    /**
     * Cancel letters that were submitted with the UploadManagement plugin and are still queued.
     *
     * @param int[] $letterIds
     *
     * @return QueuedOperationResult[]
     */
    public function cancelQueued(array $letterIds): array
    {
        return $this->queueOperation('/api/Letter/CancelQueued', $letterIds);
    }

    /**
     * Release (expedite) letters that were submitted with the UploadManagement plugin and are still queued.
     *
     * @param int[] $letterIds
     *
     * @return QueuedOperationResult[]
     */
    public function releaseQueued(array $letterIds): array
    {
        return $this->queueOperation('/api/Letter/ReleaseQueued', $letterIds);
    }

    /**
     * Status of letters sent with the PremiumAdress plugin in a date range.
     *
     * @param bool $onlyFeedback Return only letters that received PremiumAdress feedback
     *
     * @return LetterStatus[]
     */
    public function getPremiumAdressFeedback(string $fromDate, string $tillDate, bool $onlyFeedback = false): array
    {
        $body = $this->request('GET', '/api/Letter/PremiumAdressFeedback', [
            'query' => [
                'fromDate' => $fromDate,
                'tillDate' => $tillDate,
                'onlyFeedback' => self::bool($onlyFeedback),
            ],
        ]);

        return $this->statusList($body);
    }

    /**
     * Result PDF of a letter that was sent in test mode.
     *
     * @param string|null $letterId Letter ID of the test send (defaults to the current letter ID)
     */
    public function getTestResult(?string $letterId = null): LetterDataResult
    {
        $id = $letterId ?? $this->getLetterId();
        $body = $this->request('GET', '/api/Letter/TestResult', ['query' => ['letterID' => $id]]);

        return LetterDataResult::fromArray(Json::decodeObject($body));
    }

    /**
     * @param int[] $letterIds
     *
     * @return QueuedOperationResult[]
     */
    private function queueOperation(string $uri, array $letterIds): array
    {
        $body = $this->request('POST', $uri, ['json' => array_values($letterIds)]);

        return array_map(static fn(array $item) => QueuedOperationResult::fromArray($item), Json::decodeList($body));
    }

    /**
     * @return LetterStatus[]
     */
    private function statusList(string $body): array
    {
        return array_map(static fn(array $item) => new LetterStatus($item), Json::decodeList($body));
    }

    /**
     * Send a request and return the response body. 4xx responses become ErrorException.
     *
     * @param array<string, mixed> $options
     *
     * @throws ErrorException
     */
    private function request(string $method, string $uri, array $options = []): string
    {
        try {
            $response = $this->getHttpClient()->request($method, $uri, $options);
        } catch (ClientException $e) {
            throw ErrorException::fromClientException($e);
        }

        return $response->getBody()->getContents();
    }

    private function getHttpClient(): ClientInterface
    {
        if ($this->httpClient !== null) {
            return $this->httpClient;
        }

        return $this->createHttpClient([
            'base_uri' => self::API_ENDPOINT,
            'headers' => [
                'Authorization' => 'Bearer ' . $this->getAccessToken()->getToken(),
            ],
        ]);
    }

    /**
     * Create the Guzzle client used when none was injected. Override to add
     * middleware, timeouts or a different base URI.
     *
     * @param array<string, mixed> $config Guzzle client configuration
     */
    protected function createHttpClient(array $config): ClientInterface
    {
        return new HttpClient($config);
    }

    /**
     * @throws InvalidFileFormatException
     */
    private function assertPdf(string $path, string $what): void
    {
        if (!is_file($path) || !is_readable($path)) {
            throw new InvalidFileFormatException(sprintf('The %s file "%s" does not exist or is not readable', $what, $path));
        }
        if (mime_content_type($path) !== 'application/pdf') {
            throw new InvalidFileFormatException(sprintf('Unallowed file format for %s "%s". Allowed: pdf', $what, $path));
        }
    }

    /**
     * Base64 encode a file the way the API expects it (line-wrapped at 76 characters).
     */
    private function encodeFile(string $path): string
    {
        $contents = file_get_contents($path);
        if ($contents === false) {
            throw new InvalidFileFormatException(sprintf('The file "%s" could not be read', $path));
        }

        return chunk_split(base64_encode($contents));
    }

    private static function bool(bool $value): string
    {
        return $value ? 'true' : 'false';
    }
}
